[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_project = "SQTTcKM49UVhWMrctvWhaXUjvqaucdxmvAs3Ln854Cb"

[provider]
cluster = "devnet"
wallet = "/mnt/d/BlockChain/Solana/wallet-keypair.json"

[scripts]
test = "cargo test"

[hooks]
