[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_project2 = "9s48qCZpg8seSR7ejNfgYZZZiNZiSy2isCVvsCau3iJp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
