[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting2 = "27N9MNfuVWgFvg74M5WLSrYZYMRfYoEGPL8UzjPAVWB4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
