[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
voting = "BkHgcq6D9RkHMZrUL6TDn1ZrckCRWu2TJcqmXHpw6fUz"

[provider]
cluster = "devnet"
wallet = "/mnt/d/new_keypair.json"

[scripts]
test = "cargo test"

[hooks]
